---
title: "Untitled"
output: html_document
date: "2025-03-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf)
library(ggplot2)
library(dplyr)
library(sp)
```

#Reading  in the data, basic plots of the study area
```{r init}
library(viridis)

#Loading in the data and prediction grid, filtering to only group 2
load("C://Users//Shane Conroy//Downloads//helene_fit.Rdata")
load("C://Users//Shane Conroy//Downloads//helene_pred.Rdata")

hf2 <- helene_fit %>% filter(Gp == 2)
hp2 <- helene_pred %>% filter(Gp == 2)

hf2$LogPrec <- log(hf2$Prec + .1)

hf2
hp2

#Plotting study region
ggplot(data = map_data("state"), aes(x = long, y = lat, group = group)) +
  geom_polygon(fill = "gray60", color = "white") +
  geom_rect(aes(xmin = -88, xmax = -84.5, ymin = 29.5, ymax = 41),
            color = "red", fill = NA, size = 0.8) +
  coord_fixed(1.3) + labs(title = "Study Area for Hurricane Helene Storm Totals", x = 'Longitude', y = 'Latitude') + theme(
plot.title = element_text(color="red", size=14, face="bold", hjust = 0.5),
panel.background=element_rect(fill = "lightblue")
)

#Plotting Precipitation
ggplot(hf2, aes(x = Lon, y = Lat)) +
geom_polygon(data = map_data("state"), aes(x = long, y = lat, group = group),
color = "black", fill = "white", linewidth = 0.2) +
geom_point(shape = 21, aes(fill = Prec)) +
scale_fill_viridis_c(name = "Precipitation", option = "D", na.value = NA)  + 
labs(x="longitude", y="latitude",
title="Storm Totals, Hurricane Helene")+
coord_cartesian(xlim = c(-84.5, -88), ylim = c(29.5,41)) +
theme(
plot.title = element_text(color="red", size=14, face="bold", hjust = 0.5),
panel.background=element_rect(fill = "lightblue")
) + coord_sf(xlim = c(-84.5, -88), ylim = c(29.5,41), expand = FALSE)

#Plotting Log(Prec + .1)
ggplot(hf2, aes(x = Lon, y = Lat)) +
geom_polygon(data = map_data("state"), aes(x = long, y = lat, group = group),
color = "black", fill = "white", linewidth = 0.2) +
geom_point(shape = 21, aes(fill = LogPrec)) +
scale_fill_viridis_c(name = "Log Precipitation + .1", option = "D", na.value = NA)  + 
labs(x="longitude", y="latitude",
title="Storm Totals, Hurricane Helene")+
coord_cartesian(xlim = c(-84.5, -88), ylim = c(29.5,41)) +
theme(
plot.title = element_text(color="red", size=14, face="bold", hjust = 0.5),
panel.background=element_rect(fill = "lightblue")
) + coord_sf(xlim = c(-84.5, -88), ylim = c(29.5,41), expand = FALSE)
```
 

## Downloading covariates for predicitons


```{r pressure, echo=FALSE}
library(prism)
library(raster)
library(sf)
library(elevatr)

options(prism.path = "C:/Users/Shane Conroy/Documents/Prism_Data")

#Loading in the downloaded PRISM data
ppt_normals <- raster("C:/Users/Shane Conroy/Documents/Prism_Data/PRISM_ppt_30yr_normal_4kmM4_09_bil/PRISM_ppt_30yr_normal_4kmM4_09_bil.bil")

tmean_normals <- raster("C:/Users/Shane Conroy/Documents/Prism_Data/PRISM_tmean_30yr_normal_4kmM5_09_bil/PRISM_tmean_30yr_normal_4kmM5_09_bil.bil")

#Making a shapefile of our grid so we can map the PRISM data to it

grid_sp <- data.frame(Lon=hp2$Lon, Lat=hp2$Lat)

grid_sf <- st_as_sf(grid_sp, coords = c("Lon", "Lat"), crs = 4326)


#Mapping PRISM data to the shapefile

#30 year average total precipitation in the month of september (mm)
hp2$ppt <- extract(ppt_normals, grid_sf, fun = mean, na.rm = TRUE)

#30 year average temperatures in the month of september (celcius)
hp2$tmean <- extract(tmean_normals, grid_sf, fun = mean, na.rm = TRUE)

#Downloading elevation data for our prediction grid
hp2$elevation <- get_elev_point(grid_sf, src = 'aws')$elevation
```

#Downloading covariates for data
```{r}
#All this is basically the same as the last section, but we're downloading elevations/average september rainfall/average september temperature for the data she provided us

data_points_sf <- st_as_sf(hf2, coords = c("Lon", "Lat"), crs = 4326)
hf2$elevation <-get_elev_point(data_points_sf, src = "aws")$elevation
hf2$ppt <- extract(ppt_normals, data_points_sf, fun = mean, na.rm = TRUE)
hf2$tmean <- extract(tmean_normals, data_points_sf, fun = mean, na.rm = TRUE)

```

```{r}
#Regression model
model1 <- lm(data = hf2, LogPrec ~ log(ppt + .1) + tmean + poly(Lon,2, raw=TRUE) + poly(Lat,2, raw=TRUE) +
Lon:Lat + elevation)

#Predictions to be plotted
hp2$precip_total_pred=predict(model1,hp2)

ggplot(hp2) + geom_raster(aes(x=Lon, y=Lat, fill=precip_total_pred)) +
geom_polygon(data = map_data("state"), aes(x = long, y = lat, group = group),
color = "gray", fill = NA, size = 0.5) +
geom_contour(col="black", aes(x=Lon, y=Lat, z=precip_total_pred)) +
scale_fill_viridis_c(option = "magma", 
                       name = "predicted\nlog(precipitation total + .1)\n",
                       na.value = NA) +
coord_cartesian(xlim = c(-84.5, -88), ylim = c(29.5,41)) + coord_sf(xlim = c(-84.5, -88), ylim = c(29.5,41), expand = FALSE) + labs(title = 'Model 1')
```
```{r residual_stuff}
library(colorspace)

#Plotting the residuals

hf2$residuals <- model1$residuals

ggplot(hf2, aes(x = Lon, y = Lat)) +
geom_polygon(data = map_data("state"), aes(x = long, y = lat, group = group),
color = "black", fill = "white", linewidth = 0.2) +
geom_point(shape = 21, aes(fill = residuals)) +
scale_fill_continuous_divergingx(palette = 'RdBu', mid = 0) + 
labs(x="longitude", y="latitude",
title="Residual plot for regression model predicting\n total rainfall during\nhurricane helene")+
coord_cartesian(xlim = c(-84.5, -88), ylim = c(29.5,41)) +
theme(
plot.title = element_text(color="red", size=14, face="bold", hjust = 0.5),
panel.background=element_rect(fill = "lightblue")
) + coord_sf(xlim = c(-84.5, -88), ylim = c(29.5,41), expand = FALSE)
```
```{r variograms}
library(sp)
library(gstat)
#coordinates(hf2) = ~Lon + Lat

#Plotting variograms

varg <- variogram(residuals ~ 1, data = hf2, cressie=FALSE, width = .3)
plot(varg, main = 'Variogram for Precipitation Regression Model')

varg.fit.exp = fit.variogram(varg, vgm(psill = .22, "Exp", range = 2, nugget = .8))
plot(varg, model = varg.fit.exp, main='Exponential', ylim = c(0,.4))


```

